<template>
<div>
  <div class="loadingio-spinner-rolling-lw23civ0h4s"><div class="ldio-f26qsrfs4h">
  <div></div>
  </div></div>
</div>
</template>
<style type="text/css">
@keyframes ldio-f26qsrfs4h {
  0% { transform: translate(-50%,-50%) rotate(0deg); }
  100% { transform: translate(-50%,-50%) rotate(360deg); }
}
.ldio-f26qsrfs4h div {
  position: absolute;
  width: 62px;
  height: 62px;
  border: 10px solid #ffffff;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-f26qsrfs4h div {
  animation: ldio-f26qsrfs4h 1s linear infinite;
  top: 50px;
  left: 50px
}
.loadingio-spinner-rolling-lw23civ0h4s {
  width: 18px;
  height: 18px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-f26qsrfs4h {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.18);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-f26qsrfs4h div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
